### ISSUE TITLE
shell/acme_docker.sh 报错

### ISSUE THREAD

**Issue by ppllpig** [stilleshan/code#1]
已经申请成功，却显示失败，如下

jPT3/DFC3qeu/jIwCgYIKoZIzj0EAwMDaQAwZgIxALVe3tRLRMpQCMS3Cc0t0Xec
/at1nbaGF8DD/ERY7X6OtIWq9XGuKS78oH+NKh4LqQIxAPbshsy63gL3r3NQNnXT
NoljxgBGHfb5bkHnFHmcL5ga6akfLk2DQrTrEDlfMWEHFQ==
-----END CERTIFICATE-----
[Sat Jun 15 04:27:08 UTC 2024] Your cert is in: /acme.sh/sson.top_ecc/sson.top.cer
[Sat Jun 15 04:27:08 UTC 2024] Your cert key is in: /acme.sh/sson.top_ecc/sson.top.key
[Sat Jun 15 04:27:08 UTC 2024] The intermediate CA cert is in: /acme.sh/sson.top_ecc/ca.cer
[Sat Jun 15 04:27:08 UTC 2024] And the full chain certs is there: /acme.sh/sson.top_ecc/fullchain.cer
证书申请失败,请检查日志,或修改参数重新尝试.

**Comment by stilleshan** [comment]
你修改了脚本么？申请的证书是 ecc 的，和我脚本验证有冲突。

**Comment by ppllpig** [comment]
没，又试了一遍，依然这个错误。sh里手动提前填入的脚本参数，还是自动申请的ecc证书

**Comment by ppllpig** [comment]
不好意思，是这篇文章里的，以为是你的
https://blog.csdn.net/qq_33689316/article/details/137437917

**Comment by stilleshan** [comment]
> 不好意思，是这篇文章里的，以为是你的 https://blog.csdn.net/qq_33689316/article/details/137437917

这篇是参考我的，不过这个链接是老版本，有这个ecc问题，用新的

https://gist.github.com/stilleshan/02d8652ce320941e497d378a04ecf016

https://gist.githubusercontent.com/stilleshan/02d8652ce320941e497d378a04ecf016/raw/0715d5a38d3a11ecaaa2d2a22aee2d087ef1e630/acme_docker.sh
